---
- name: Gather Cisco IOS/IOSXE Inventory Facts
  gather_facts: false
  hosts: all
  tasks:
    - name: Collect Facts
      ios_facts:
        gather_subset: "!config"
        register: cisco_facts
      debug:
        msg: "{{cisco_facts.ansible_net_version}}"
