---
- name: Gather Cisco IOS/IOSXE Inventory Facts
  gather_facts: false
  hosts: CISCO
  tasks:
    - name: Collect Facts
      ios_facts:
        gather_subset: 
          - "!config"
      register: cisco_facts
    - name: Print Version
      debug:
        msg: "{{cisco_facts.ansible_facts.ansible_net_version}}"
