---
- name: Gather Cisco IOS/IOSXE Inventory Facts
  gather_facts: false
  hosts: CISCO
  tasks:
    - name: Collect Facts
      debug:
        msg: "{{ansible_net_version}}"
    #   ios_facts:
    #     gather_subset: 
    #       - "!config"
    #   register: facts
    # - set_fact:
    #    ios_version: "{{facts.ansible_facts.ansible_net_version}}"
