---
- name: Gather Cisco IOS/IOSXE Inventory Facts
  gather_facts: false
  hosts: CISCO
  tasks:
    - name: Collect Facts
      ios_facts:
        gather_subset: 
          - "!config"
    - set_fact:
       ios_version: "{{ansible_facts.ansible_net_version}}"
